#!/bin/bash

TEST_DIR="test_cases"
EXEC_DIR="../src"
TMP_DIR="/tmp"

RED='\033[0;31m'
GREEN='\033[0;32m'
NOCOLOR='\033[0m'
DIM='\e[2m'
TICK='\u2713'
CROSS='\u2717'

function cleanup() {
    rm -f $TMP_DIR/compiler_stderr $TMP_DIR/interpreter_stderr $TMP_DIR/output
}

function show() {
    for test in "$TEST_DIR"/*; do
        echo -e "$(basename "$test")$DIM"
        cat "$test"/description.txt
        echo -e "$NOCOLOR"
    done
}

function generate() {
    test="$TEST_DIR"/"$1"
    # If any of the crucial files is missing, exit
    [ -f "$test"/program.tl ] || {
        echo "Cannot generate, $test/program.tl is missing"
        exit 1
    }

    touch "$test"/input
    touch "$test"/input

    # Ask user to enter description
    [ -f "$test"/description.txt ] || {
        echo "The description file is missing. Enter it now:"
        read -r
        echo "${REPLY}" >"$test"/description.txt
    }

    # Run the compiler
    ./$EXEC_DIR/compiler <"$test"/program.tl >$TMP_DIR/out.IFJcode21 2>$TMP_DIR/compiler_stderr
    compilerReturn=$?

    # Did the compiler finish successfully?
    if [ $compilerReturn -eq 0 ]
    then
        # Run the interpreter
        ./$EXEC_DIR/ic21int $TMP_DIR/out.IFJcode21 <"$test"/input >"$test"/output 2>$TMP_DIR/interpreter_stderr
        interpreterReturn=$?
        echo $interpreterReturn > "$test"/return
    else
        echo $interpreterReturn > "$test"/return
    fi
}

[ "$1" ] && [ "$1" = "s" ] || [ "$1" = "show" ] && show && exit 0
[ "$1" ] && [ "$1" = "g" ] || [ "$1" = "generate" ] && generate "$2" && exit 0

numTests=0
numTestsPassed=0

for test in "$TEST_DIR"/*; do
    passed=''
    expectedReturn="$(cat "$test"/return)"

    # Run the compiler
    ./$EXEC_DIR/compiler <"$test"/program.tl >$TMP_DIR/out.IFJcode21 2>$TMP_DIR/compiler_stderr
    compilerReturn=$?

    # Did the compiler finish successfully?
    if [ $compilerReturn -eq 0 ]
    then
        # Run the interpreter
        ./$EXEC_DIR/ic21int $TMP_DIR/out.IFJcode21 <"$test"/input >$TMP_DIR/output 2>$TMP_DIR/interpreter_stderr
        interpreterReturn=$?

        # Did the interpreter finish successfully?
        if [ $interpreterReturn -eq 0 ]
        then
            # Does the output match with reference? Expected return must be zero.
            diff --strip-trailing-cr "$TMP_DIR/output" "$test"/output >$TMP_DIR/diff_output \
            && [ "$(cat "$test"/return)" -eq 0 ] \
            && passed='1'
        else
            # Does the runtime error match with reference?
            [ $interpreterReturn -eq "$expectedReturn" ] && passed='1'
        fi
    else
        # Does the compiler error match the reference?
        [ $compilerReturn -eq "$expectedReturn" ] && passed='1'
    fi

    if [ $passed ]; then
        echo -e "$GREEN$TICK $(basename "$test")$NOCOLOR"
        numTestsPassed=$((numTestsPassed+1))
    else
        echo -e "$RED$CROSS $(basename "$test")$DIM"

        # Print more detailed error info
        cat "$test"/description.txt

        if [ "$expectedReturn" -eq 0 ]
        then
            if [ $compilerReturn -ne 0 ]
            then
                echo "Compiler exited with error $compilerReturn:"
                cat $TMP_DIR/compiler_stderr
            else
                if [ $interpreterReturn -ne 0 ]
                then
                    echo "Interpreter exited with error $interpreterReturn:"
                    cat $TMP_DIR/interpreter_stderr
                else
                    echo Expected output:
                    cat "$test"/output
                    echo Output:
                    cat $TMP_DIR/output
                fi
            fi
        else
            echo "Program was supposed to fail, but with different exit code"
            echo "Expected return: $expectedReturn" \
            && echo "Compiler return: $compilerReturn" \
            && [ $compilerReturn -eq 0 ] && echo "Interpreter return: $interpreterReturn"
        fi
        echo -ne "$NOCOLOR"
    fi
    numTests=$((numTests+1))
done

# After all tests, print summary
if [ $numTestsPassed -eq $numTests ]
then
    echo -e "\n$GREEN$TICK ALL TESTS PASSED$NOCOLOR"
else
    echo -e "\n$RED$CROSS SOME TESTS FAILED ($numTestsPassed/$numTests passed)$NOCOLOR"
fi
